services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
#            $pluginDirectory: "%kimai.plugin_dir%"
            $dataDirectory: "%kimai.data_dir%"
    KimaiPlugin\EasyBackupBundle\:
        resource: '../../*'
        exclude: '../../{Resources}'
